
package org.prosur.catalog.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CatalogFault", targetNamespace = "http://ws.catalog.prosur.org/")
public class CatalogFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CatalogFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CatalogFault_Exception(String message, CatalogFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CatalogFault_Exception(String message, CatalogFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.prosur.catalog.ws.CatalogFault
     */
    public CatalogFault getFaultInfo() {
        return faultInfo;
    }

}
