
package org.prosur.catalog.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProsurIPRecordWSService", targetNamespace = "http://ws.catalog.prosur.org/", wsdlLocation = "file:/home/archie/prosur.wsdl")
public class ProsurIPRecordWSService
    extends Service
{

    private final static URL PROSURIPRECORDWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROSURIPRECORDWSSERVICE_EXCEPTION;
    private final static QName PROSURIPRECORDWSSERVICE_QNAME = new QName("http://ws.catalog.prosur.org/", "ProsurIPRecordWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/archie/prosur.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROSURIPRECORDWSSERVICE_WSDL_LOCATION = url;
        PROSURIPRECORDWSSERVICE_EXCEPTION = e;
    }

    public ProsurIPRecordWSService() {
        super(__getWsdlLocation(), PROSURIPRECORDWSSERVICE_QNAME);
    }

    public ProsurIPRecordWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROSURIPRECORDWSSERVICE_QNAME, features);
    }

    public ProsurIPRecordWSService(URL wsdlLocation) {
        super(wsdlLocation, PROSURIPRECORDWSSERVICE_QNAME);
    }

    public ProsurIPRecordWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROSURIPRECORDWSSERVICE_QNAME, features);
    }

    public ProsurIPRecordWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProsurIPRecordWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProsurIPRecordWS
     */
    @WebEndpoint(name = "ProsurIPRecordWSPort")
    public ProsurIPRecordWS getProsurIPRecordWSPort() {
        return super.getPort(new QName("http://ws.catalog.prosur.org/", "ProsurIPRecordWSPort"), ProsurIPRecordWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProsurIPRecordWS
     */
    @WebEndpoint(name = "ProsurIPRecordWSPort")
    public ProsurIPRecordWS getProsurIPRecordWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.catalog.prosur.org/", "ProsurIPRecordWSPort"), ProsurIPRecordWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROSURIPRECORDWSSERVICE_EXCEPTION!= null) {
            throw PROSURIPRECORDWSSERVICE_EXCEPTION;
        }
        return PROSURIPRECORDWSSERVICE_WSDL_LOCATION;
    }

}
